title: Hyperliquid Việt Nam
source: .
destination: _site

collections_dir: content

collections:
  blog:
    output: true
    permalink: /blog/:slug/
  news:
    output: true
    permalink: /news/:slug/

defaults:
  - scope:
      path: "blog"
      type: "blog"
    values:
      layout: blog
  - scope:
      path: "news"
      type: "news"
    values:
      layout: blog
