title: Hyperliquid Việt Nam
description: Cộng đồng hàng đầu và nguồn thông tin cập nhật về Hyperliquid tại Việt Nam
url: "https://hyperliquidvietnam.xyz"
source: .
destination: _site

collections_dir: content

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-og-image

og_image:
  theme: dark
  font_size: 72
  background: '#0f2126'

sass:
  style: compressed

collections:
  blog:
    output: true
    permalink: /blog/:slug/
  news:
    output: true
    permalink: /news/:slug/

defaults:
  - scope:
      path: "blog"
      type: "blog"
    values:
      layout: blog
  - scope:
      path: "news"
      type: "news"
    values:
      layout: blog
