title: Hyperliquid Việt Nam
source: .
destination: _site

collections:
  blog:
    output: true
    source: content/blog
    permalink: /blog/:slug/
  news:
    output: true
    source: content/news
    permalink: /news/:slug/

defaults:
  - scope:
      path: "content/blog"
      type: "blog"
    values:
      layout: blog
  - scope:
      path: "content/news"
      type: "news"
    values:
      layout: blog
